services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: transport_app_server
    expose:
      - '3000'
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm start
